### ISSUE TITLE
Heatmap data is always plotted at 0 start time despite timestamps

### ISSUE THREAD

**Issue by jonahpearl** [calebweinreb/SNUB#1]
Code to reproduce is below; compare SNUB viewer with offset=0 and offset=150. I looked into the add_heatmap function and that looked like it was correct, so the bug is probably deeper and I don't want to dig around to find it. 

Issue solved for now just by zeroing all timestamps.

```
offset = 150
data = np.random.random((3,300))
times = np.arange(300) + offset

project_directory = './fr_debug'
snub.io.create_project(
    project_directory,
    start_time=float(times[0]),
    end_time=float(times[-1]),
    min_step=1,
    overwrite=True)

snub.io.add_heatmap(project_directory,
                    'debug',
                    data,
                    start_time=times[0],
                    binsize=1
                   )
```

**Comment by calebweinreb** [comment]
Thanks. Fixed in https://github.com/calebweinreb/SNUB/commit/b598d71b534d4c72ed3aadc39106b2993ecd8f3f
