### ISSUE TITLE
[Minor] DOI for datasets

### ISSUE THREAD

**Issue by vigji** [calebweinreb/SNUB#10]
Currently, documentation points at dropbox folders to download the example datasets. Maybe I am wrong, but I believe that does links do not have the stability that would be warranted by a DOI-minting data storage. 

I would strongly advise to keep the data on places like Zenodo or Figshare and link them via DOI addresses.

**Comment by calebweinreb** [comment]
The example datasets have now been deposited on Zenodo https://doi.org/10.5281/zenodo.10578025
