### ISSUE TITLE
[Minor] Icon attribution

### ISSUE THREAD

**Issue by vigji** [calebweinreb/SNUB#14]
As far as I can see, the icon is a schematic from scidraw (full disclosure, one I draw!), and [the licence](https://creativecommons.org/licenses/by/4.0/#ref-appropriate-credit) under which the image is free to use would require a small attribution somewhere.

**Comment by calebweinreb** [comment]
My apologies for the oversight, and thanks for contributing the drawing! I added an acknowledgement in the paper (https://github.com/calebweinreb/SNUB/commit/167511c5bbe5b6c701d718c2b7cd85d9f6915d7a).

**Comment by vigji** [comment]
No problem! Putting it in the paper is maybe to much as it conflates it with actual codebase sources, a very small link in the docs somewhere suffices if you prefer! But up to you :)
