### ISSUE TITLE
[Minor] Linting

### ISSUE THREAD

**Issue by vigji** [calebweinreb/SNUB#15]
The code seems to not have been passed through any linting tool (such as flake8) to remove minor departures from PEP recommendations (eg, unused imports, unused arguments in functions). To make it publishable-quality, I would recommend including some linting tool in the workflow to iron those out.

**Comment by calebweinreb** [comment]
Thanks for the suggestion! I used black to reformat the code and VS code to highlight unused imports (which were deleted) (https://github.com/calebweinreb/SNUB/commit/aee2d2adb4a5eba6938550e89898c60b1dac2162). I know some projects also include these kinds of checks as github actions but I think that might be overkill here as I am currently the only active developer.
