### ISSUE TITLE
[SUGGESTION] Consider making development dependencies optional

### ISSUE THREAD

**Issue by niksirbi** [calebweinreb/SNUB#19]
Some of the dependencies, e.g. `pytest` and `pytest-qt` are only required during development, and not needed for users. You could [make those dependencies optional](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) under an arbitrary identifier (e.g. `dev`) in your `setup.cfg` file.

```
[options.extras_require]
dev =
    pytest
    pytest-qt
```

This way `pip install systems-neuro-browser` will install only the smaller set of "normal" dependencies, whereas `pip install systems-neuro-browser[dev]` will also include the testing dependencies. In future, if you add linters and or type checking, you could also group those tools under the. `dev` optional dependencies.

**Comment by calebweinreb** [comment]
I implemented the dev option exactly as described (https://github.com/calebweinreb/SNUB/commit/7c130749962e90ddbc63207441aaa6dc203d5fa9). Its now available on PyPI for version >= 0.0.14
