### ISSUE TITLE
[MAJOR] Missing contributing guide

### ISSUE THREAD

**Issue by niksirbi** [calebweinreb/SNUB#20]
@calebweinreb you seem to be the only developer at the moment, but I assume that you would like for the project to grow and to inspire contributions from collaborators, and perhaps also from the wider systems neuro community.

I suggest adding a `CONTRIBUTING.md` guide to the repo and, at the minimum, stating your policy on external contributions. Are they welcome, and if so, what's the recommended procedure?

**Comment by calebweinreb** [comment]
I've now added a contribution guide:

https://github.com/calebweinreb/SNUB/blob/main/CONTRIBUTING.md

**Comment by niksirbi** [comment]
Thanks! I'll close this issue.
