### ISSUE TITLE
[SUGGESTION] Ability to add and remove dataviews in the GUI

### ISSUE THREAD

**Issue by niksirbi** [calebweinreb/SNUB#22]
Currently, users have to first create a project by adding all relevant data sources via functions like `snub.io.add_video`, `snub.io.add_scatter` etc. Once a project is created and opened, there is no way to add more data sources as views directly in the GUI. It would be nice to initialise a project with a few views, and be able to add more as you see fit.

In other words, I would like for the `add_` methods to be exposed in the GUI, perhaps under the "File" menu.  It would also be nice to have the option to close data views in the GUI (e.g. via an 'X' button on each panel).

This is more of an idea for a possible future direction. Feel free to dismiss if you think it would complicate things too much.

**Comment by calebweinreb** [comment]
I like this idea! Adding an "X" button for closing a widget is easy and will be included in the next release (implemented here https://github.com/calebweinreb/SNUB/pull/25). 

Adding new widgets through the GUI is a little more of a lift so I may wait to see if it is requested by anyone else. But in principle I could definitely imagine a generic widget that programmatically exposes the args/kwargs for each respective add_ function.

**Comment by vigji** [comment]
I agree that this would be a great functionality to add!
