### ISSUE TITLE
[Minor] Some typos I found in the paper and the docs

### ISSUE THREAD

**Issue by niksirbi** [calebweinreb/SNUB#24]
## Paper
- Line 24: `dislay`
- Line 31: `snub.io.add_splikeplot`

## Docs
- Homepage: `snub.io.add_splikeplot`
- Calcium imaging tutorial: `There are also a behavior annotations` (the "a" should be removed).

**Comment by calebweinreb** [comment]
Wow thank you for catching these! Fixed here https://github.com/calebweinreb/SNUB/commit/389dde73608ff707c720cb2e053fc66d789083d6
