### ISSUE TITLE
Unable to load video with separate path

### ISSUE THREAD

**Issue by NeuTTH** [calebweinreb/SNUB#32]
I am trying to construct a project with the video placed in another folder. There is no issue when loading all the configs in, but the video can never be loaded at the browser. I traced the issue to [here](https://github.com/calebweinreb/SNUB/blob/e5e5caae3904b23aac34c8d7d9763a2abe779b34/snub/gui/panels/video.py#L35), where I think the code should be 

```
        self.video_frame = VideoFrame(video_path)
``` 
since video_path can technically be anywhere. 

There is also a related issue where the copy option of the [add_video](https://github.com/calebweinreb/SNUB/blob/e5e5caae3904b23aac34c8d7d9763a2abe779b34/snub/io/project.py#L401) function is not implemented correctly. In this [line](https://github.com/calebweinreb/SNUB/blob/e5e5caae3904b23aac34c8d7d9763a2abe779b34/snub/io/project.py#L506) it is just assuming the video is in the same directory as the project directory.

Thanks!

Best,
Dexter

**Comment by calebweinreb** [comment]
Thanks for catching this! I have created [a separate PR](https://github.com/calebweinreb/SNUB/pull/36) for this that addresses the bug in `add_video` but in a way that maintains consistency with the path logic for other widgets. Let me know if it works for you.

**Comment by NeuTTH** [comment]
Thanks! this works. Will close the issue and pull
