### ISSUE TITLE
Unable to draw area and select relevant area in UMAP embedding in mac 

### ISSUE THREAD

**Issue by NeuTTH** [calebweinreb/SNUB#34]
it was described in the [documentation](https://snub.readthedocs.io/en/latest/gui.html#use-selections) where one can draw area on UMAP embedding and select relevant clusters. I have tried working on both windows and mac machine, but it seems only the former works. The behavior persists whether in trackpad or mouse, where I will just drag the clusters around instead of drawing any squares. The scrolling function is also working properly.

I am working with a Macbook pro with apple silicon, and macOS 14.2.1 . I followed the instructions on the installation page for normal installation (python=3.8), and my snub version is 0.0.12 . There are also no errors messages popping up.

**Comment by calebweinreb** [comment]
I'll look into this. Two quick questions:
1) Does the shaded rectangle appear but nothing gets selected? Or the rectangle doesn't even appear?
2) Can you confirm that you are holding down the Shift key while dragging?

**Comment by NeuTTH** [comment]
Sorry, with shift it does work! When I tried to select on windows I wasn't using shift and it still allows me to draw the rectangle. Will close this issue.
